[package]
name = "pnghider"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
crc = "3.2.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
url = "2.5.2"
